{
    "name": "Reminder",
    "version": "0.0.1",
    "icon": "fab fa-battle-net",
    "category": "undefined",
    "author": "Psychokiller1888",
    "maintainers": [],
    "desc": "Ask alice to remind you stuff at a given time",
    "aliceMinVersion": "1.0.0-a6",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "asrArbitraryCapture": true
    }
}